version: '3'

services:
  cicero:
    build: .
    image: cicero
    networks:
      - cicero-netw
    deploy:
      resources:
        reservations:
          devices:
            - driver: ""
              capabilities: [gpu]
    volumes:
      - calcio:/code

volumes:
  calcio:
    driver: local
    driver_opts:
      type: none
      device: ./calcio
      o: bind

networks:
  cicero-netw:
    driver: overlay
    attachable: true